/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function untarLzma(input: string, output: string): boolean
export function untarBzip2(input: string, output: string): boolean
