/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function untar(input: string, output: string): boolean
export function tar(input: string, output: string, compressionType: number): boolean
